# Generated by Django 4.2.3 on 2023-08-06 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontienda', '0002_remove_tienda_productotienda_producto_productotienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='productoTienda',
        ),
        migrations.AddField(
            model_name='producto',
            name='tiendaProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiontienda.tienda'),
        ),
    ]
